# Datasource (Postgres dans ton cas)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=payza_app
quarkus.datasource.password=P@yZ4_S3cReT5!
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/payza
quarkus.hibernate-orm.physical-naming-strategy.table-name-prefix=pz_
quarkus.hibernate-orm.database.generation=update
# Or drop-and-create
quarkus.swagger-ui.path=/docs

# JWT
smallrye.jwt.new-token.issuer=granix-payza

smallrye.jwt.sign.key.location=privateKey.pem 
smallrye.jwt.sign.algorithm=RS256
mp.jwt.verify.publickey.location=publicKey.pem

mp.jwt.verify.issuer=granix-payza
# OpenAPI
quarkus.smallrye-jwt.enabled=true

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

# Application
payza.crypto.algo=AES
payza.crypto.tag-length=128
payza.crypto.byte-key=12345678901234567890123456789012
payza.crypto.byte-iv=123456789012

# Payza IBAN Configuration
payza.iban.default-bank-code=PAYZ
payza.iban.default-branch-code=001

# Madagascar
payza.iban.countries.MG.length=27
payza.iban.countries.MG.branch-code=001
payza.iban.countries.MG.bank-codes.MGA=PAYZ

# South Africa
payza.iban.countries.ZA.length=25
payza.iban.countries.ZA.branch-code=001
payza.iban.countries.ZA.bank-codes.ZAR=PAYZ

# Kenya
payza.iban.countries.KE.length=25
payza.iban.countries.KE.branch-code=001
payza.iban.countries.KE.bank-codes.KES=PAYZ

# Tanzania
payza.iban.countries.TZ.length=25
payza.iban.countries.TZ.branch-code=001
payza.iban.countries.TZ.bank-codes.TZS=PAYZ

# Senegal
payza.iban.countries.SN.length=28
payza.iban.countries.SN.branch-code=001
payza.iban.countries.SN.bank-codes.XOF=PAYZ

# Cameroon
payza.iban.countries.CM.length=27
payza.iban.countries.CM.branch-code=001
payza.iban.countries.CM.bank-codes.XAF=PAYZ

